services:
  mongo:
    image: mongo:7.0
    container_name: oqueeisso_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

  app:
    build: .
    container_name: oqueeisso_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/oqueeisso
      - JWT_SECRET=oqueeisso_super_secret_jwt_key_2026_artesanato
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
