services:
  mongo:
    image: mongo:7.0
    container_name: oqueeisso-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build: .
    container_name: oqueeisso-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/oqueeisso
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      app-network:
      proxy:
        aliases:
          - oqueeisso-app
          - oqueeisso_app
          - oqueeisso

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
  proxy:
    external: true


